services:
#    backend.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    following.twig_extension:
        class: AppBundle\Twig\FollowingExtension
        public: false
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }